export const FETCH_U_REQUEST = "FETCH_U_REQUEST";
export const FETCH_U_SUCCESS = "FETCH_U_SUCCESS";

export const FETCH_REGISTRATION_ERROR = "FETCH_REGISTRATION_ERROR";
export const FETCH_AUTHORIZATION_ERROR = "FETCH_AUTHORIZATION_ERROR";
export const SET_USER_DATA = "SET_USER_DATA";
